### ISSUE TITLE
[JOSS review] Error when running in Windows Subsystem for Linux (WSL 2)

### ISSUE THREAD

**Issue by janfreyberg** [ZeitgeberH/patchview#6]
Hi,

after installing patchview using pip on WSL, I received the following error when running the `patchview` command:

<details>
  <summary>AttributeError: 'NoneType' object has no attribute 'eglGetCurrentContext'</summary>

```error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/patchview/__init__.py", line 1, in <module>
    from . import patchview
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/patchview/patchview.py", line 7, in <module>
    import pyqtgraph.opengl as gl
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/pyqtgraph/opengl/__init__.py", line 1, in <module>
    from . import shaders
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/pyqtgraph/opengl/shaders.py", line 1, in <module>
    from OpenGL.GL import *  # noqa
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 4, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_1_1.py", line 14, in <module>
    from OpenGL.raw.GL.VERSION.GL_1_1 import *
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/raw/GL/VERSION/GL_1_1.py", line 7, in <module>
    from OpenGL.raw.GL import _errors
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module>
    _error_checker = _ErrorChecker( _p, _p.GL.glGetError )
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/error.py", line 183, in __init__
    self._isValid = platform.CurrentContextIsValid
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 356, in CurrentContextIsValid
    return self.GetCurrentContext
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 15, in __get__
    value = self.fget( obj )
  File "/home/jan/joss-reviews/patchview/install-env/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 106, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
AttributeError: 'NoneType' object has no attribute 'eglGetCurrentContext'
```
</details>

I suspect this might be related to using WSL, and this being a GUI application. Unless this is a real dependency problem on Linux (unfortunately, I don't have a "real" Linux installation), I suggest adding a disclaimer to the documentation that patchview does not run on WSL.

**Comment by ZeitgeberH** [comment]
Hi Jan,
I can confirm that `patchview` can be installed in WSL/WSL2 under windows 10, but the GUI would not launch.  Wsl2 on Windows 11 may work, but I currently do not have access to Windows 11. 
I've run `patchview` successfully on Ubuntu 18.04 LTS and Mac Catalina.
These has been documented (in [Get started/Pip install/note 2](https://patchview.readthedocs.io/en/latest/installation.html#test-dataset)) as you suggested above.
Thank you!
Zeta
